### ISSUE TITLE
[M5-SX127x] CS_PIN value for CoreS3

### ISSUE THREAD

**Issue by lboue** [m5stack/M5-SX127x#1]
Hello,

I'd like to test my module `LoRa868_V1.1` with a CoreS3. So I need to change the `CS_PIN` value in the example file. 

https://github.com/m5stack/M5-SX127x/blob/87c9694bf486c94d835a74d481fdd32d0aa9123c/examples/LoRaSender/LoRaSender.ino#L9-L16

However, I can't find this `CS_PIN` pin either in the documentation or on the module itself?

![image](https://github.com/user-attachments/assets/08f4d579-7c58-4acf-b54b-cafc3f4dcd81)

![image](https://github.com/user-attachments/assets/d79ac9be-cc75-4405-8731-1e3586eca934)

Could you help me?

Regards

**Comment by TinyuZhao** [comment]
NSS Pin = CS Pin.
You can select 1/6/10/0 as the CS pin through the DIP switch

**Comment by lboue** [comment]
Thanks
